In [24]:
import pandas as pd
import numpy as np

In [27]:
pd.__version__

'3.0.5'

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [29]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [30]:
print(len(df))

10000

In [9]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [31]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [32]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [23]:
# Step 1: Calculate the initial median
initial_median = df['horsepower'].median()

# Step 2: Calculate the most frequent value (mode)
most_frequent_value = df['horsepower'].mode()[0]

# Step 3: Fill missing values with the most frequent value
df['horsepower'] = df['horsepower'].fillna(most_frequent_value)

# Step 4: Calculate the median again
new_median = df['horsepower'].median()

# Step 5: Print results to see if it changed
print(f"Initial Median: {initial_median}")
print(f"Most Frequent Value (Mode): {most_frequent_value}")
print(f"New Median: {new_median}")

if new_median > initial_median:
    print("Answer: Yes, it increased")
elif new_median < initial_median:
    print("Answer: Yes, it decreased")
else:
    print("Answer: No")

Initial Median: 252.0
Most Frequent Value (Mode): 252.0
New Median: 252.0
Answer: No

In [35]:
# 1. Select all cars from Asia
asia_cars = df[df['origin'] == 'Asia']
asia_cars

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [36]:
# 2. Select only columns vehicle_weight and model_year, and get the first 7 values
X_df = asia_cars[['vehicle_weight', 'model_year']].head(7)
X_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [40]:
# 3. Get the underlying NumPy array
X = X_df.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [42]:
# 4. Compute XTX (Matrix multiplication of X transpose and X) 
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [44]:
# 5.invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [45]:
# 6. Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [46]:
# 7. Multiply the inverse of XTX with the transpose of X, and then by y to get w
w = XTX_inv @ X.T @ y
print("Weights (w):", w)

Weights (w): [0.13644777 0.2327492 ]

In [48]:
# 8. What's the sum of all the elements of the result?
total_sum = w.sum()
print(f"Sum of all elements: {total_sum}")

Sum of all elements: 0.36919696904925486